### ISSUE TITLE
Import * is not considered good practice

### ISSUE THREAD

**Issue by PySimpleGUI** [sigmf/SigMF#199]
Using an import * for PySimpleGUI needlessly pollutes your namespace.  I know a lot of tkinter examples out on the internet do it, but it's because they get copied around, not because it's a good idea.

Thanks for using PySimpleGUI!

![image](https://user-images.githubusercontent.com/46163555/144504216-2fdec8c7-5be2-4038-9c20-b0c0f8fefa5b.png)

**Comment by jacobagilbert** [comment]
Thanks for the issue.

It seems our GUI application also has some other issues; when I run it:

```python
jacob@jacob-ds1:/opt/sigmf/SigMF$ sigmf_gui 
/home/jacob/.local/lib/python3.8/site-packages/PySimpleGUI/PySimpleGUI.py:1443: UserWarning: You cannot Update element with key = Update until the window.read() is called or finalized=True when creating window
  warnings.warn('You cannot Update element with key = {} until the window.read() is called or finalized=True when creating window'.format(self.Key),
/home/jacob/.local/lib/python3.8/site-packages/PySimpleGUI/PySimpleGUI.py:1443: UserWarning: You cannot Update element with key = Load Archive until the window.read() is called or finalized=True when creating window
  warnings.warn('You cannot Update element with key = {} until the window.read() is called or finalized=True when creating window'.format(self.Key),
/home/jacob/.local/lib/python3.8/site-packages/PySimpleGUI/PySimpleGUI.py:1443: UserWarning: You cannot Update element with key = Save Archive until the window.read() is called or finalized=True when creating window
  warnings.warn('You cannot Update element with key = {} until the window.read() is called or finalized=True when creating window'.format(self.Key),
```

**Comment by PySimpleGUI** [comment]
The error pretty much tells you what's happening.  

I'm not sure where the original code came from that you're using as examples, but it's VERY old design patterns that were replaced a long time ago.  None of the Demo Programs, Cookbook, etc, use things like `.Layout(layout)`.  Calls that are not PEP8 compliant were replaced a long time back too like `Window.Read` versus `Window.read`.

The call reference portion of the documentation groups together these non-PEP8 calls and explains they aren't recommended now.

If you need support for things like the above warnings, by all means open an issue on the PySimpleGUI GitHub (HTTP://Issues.PySimpleGUI.org).  You can also open an Issue using the GUI built into PySimpleGUI.  Call `sg.main()` and you'll see a button to open an issue.

**Comment by jacobagilbert** [comment]
Thanks for the extra detail. I'm not particularly familiar with the GUI we have but it will most likely get fixed (or replaced) after we get our specification 1.0 release out.

**Comment by PySimpleGUI** [comment]
![image](https://user-images.githubusercontent.com/46163555/145684786-fe5a36a6-8b7b-42d7-a605-4405845893ed.png)

**Comment by jacobagilbert** [comment]
Closing this since this code has moved, a reference to it is included here https://github.com/sigmf/sigmf-python/issues/7 in a slightly more encompassing issue.
