### ISSUE TITLE
Dataset Format

### ISSUE THREAD

**Issue by IM-USAF** [sigmf/SigMF#283]
It's not clear to me since delimiters are mentioned. Is the dataset format binary?

**Comment by Teque5** [comment]
Not exactly sure what you mean, but here are some examples from the spec:

> So, for example, the string "cf32_le" specifies "complex 32-bit floating-point samples stored in little-endian", the string "ru16_be" specifies "real unsigned 16-bit samples stored in big-endian", and the string "cu8" specifies "complex unsigned byte".

The field `core:dataset` is a `str`. The `-data` file itself containing RF samples is packed binary as described by the `-meta` file.

**Comment by Teque5** [comment]
Closing for now. If you have specific questions open an issue in the [new repo](https://github.com/sigmf/sigmf-python).
