### ISSUE TITLE
Does captures array require at least 1 item?

### ISSUE THREAD

**Issue by 777arc** [sigmf/SigMF#291]
Doesn't make it clear in the specs

**Comment by jacobagilbert** [comment]
This should be explicit.

The implicit behavior right now is that if there are no defined captures, everything exists in a single capture segment with no metadata.

**Comment by 777arc** [comment]
"no metadata" meaning no captures-specific metadata?

**Comment by jacobagilbert** [comment]
Correct.

**Comment by 777arc** [comment]
Alright I'll get this added as a PR, it will be more along the lines of "highly discouraged but not technically invalid sigmf, tooling should assume "captures": [{"core:sample_start": 0, "core:frequency": 0}] if it doesn't find a captures key.  Sound OK?

**Comment by jacobagilbert** [comment]
I dont think `core:frequency` is implied here.

**Comment by 777arc** [comment]
Ah my bad, forgot freq was optional.  `"captures": [{"core:sample_start": 0}]`

**Comment by jacobagilbert** [comment]
Cool, I'd support merging a small language clarification here.
