### ISSUE TITLE
Reference to `core:data_type` instead of `core:datatype` in `sigmf-spec.md`

### ISSUE THREAD

**Issue by BatchDrake** [sigmf/SigMF#302]
Hi,

The document `sigmf-spec.md` references a nonexistent key in the core namespace named `core:data_type`. This is probably a minor, as it appears only once and looks like a misspelling of `core:datatype`:

> Complex samples MUST be interleaved, with the in-phase component first (i.e., I[0] Q[0] I[1] Q[1] ... I[n] Q[n]). When core:num_channels in the Global Object (described below) indicates that the Recording contains more than one channel, samples from those channels MUST be interleaved in the same manner, with the same index from each channel's sample serially in the Recording. For example, a Recording with two channels of ri16_le representing real-valued audio data from a stereo Recording and here labeled L for left and R for right, the data MUST appear as L[0] R[0] L[1] R[1] ... L[n] R[n]. The data type specified by `core:data_type` applies to all channels of data both real and imaginary parts.

Cheers,

**Comment by 777arc** [comment]
Nice catch!!!
