### ISSUE TITLE
capture_details extension: "attentuation" typo

### ISSUE THREAD

**Issue by SureshotM6** [sigmf/SigMF#307]
https://github.com/sigmf/SigMF/blob/a6eb9d7bb05455eeb5cfff75bffe0b64dc827064/extensions/capture_details.sigmf-ext.md?plain=1#L18

The key should be "attenuation" not "attentuation".  It is spelled correctly in the description.  Unfortunately this would not be a backward-compatible change.
If it is decided to not change this to maintain compatibility then the typo should at least be called out in the description, as this can easily cause bugs for generators or parsers that may have correctly spelled "attenuation."

**Comment by jacobagilbert** [comment]
Extension namespaces are slightly less rigid... this definitely does need to be fixed.
