### ISSUE TITLE
Dataset file in same metadata directory instead of local directory

### ISSUE THREAD

**Issue by lgoix** [sigmf/SigMF#321]
I think there is an issue with the dataset description in SigMF Specification Version v1.2.2
https://sigmf.org/#ssubsec:dataset

> The Dataset file must be in the local directory, and this string MUST NOT include any aspects of filepath other than the filename.

If I am running a script in `/home/user/`  and I open the `signal.sigmf-meta` file in the directory `/media/usb1/`, the specification is telling us the dataset file has to be in the local directory, ie:  `/home/user/`

I would suggest to modify the dataset specification to specify that the Dataset file must be in the same directory than the .sigmf-meta file.

**Comment by 777arc** [comment]
Good catch, it was always meant to refer to the same dir as meta, not some arbitrary local dir, I'll fix the wording

**Comment by 777arc** [comment]
@lgoix note that that field is specific to NCD, which we tend to avoid using anyway

**Comment by lgoix** [comment]
I started to update the sigmf-python module to find the file, but I wanted the Spec to be updated before.
