### ISSUE TITLE
Missing clarification for empty captures array

### ISSUE THREAD

**Issue by bbc131** [sigmf/SigMF#326]
PR #293 explicitly added some clarification, that there should be at last one element in the captures array, but doesn't have to.
I'm not sure if this was intentionally dropped with #301, but for me this clarification was justified and is missing now.

**Comment by 777arc** [comment]
Ah nice catch, I'll get it added back in

**Comment by 777arc** [comment]
https://github.com/sigmf/SigMF/pull/327
